# MSSQL Database Configuration
quarkus.datasource.db-kind=mssql
quarkus.datasource.jdbc.url=jdbc:sqlserver://10.0.2.134:1433;databaseName=TrainingDec2024;encrypt=false
quarkus.datasource.username=trainingusertns
quarkus.datasource.password=TNStu@2025
quarkus.datasource.jdbc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate settings
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=true


# Enable JSON logging in console and file
quarkus.log.console.json=true
quarkus.log.file.enable=true
quarkus.log.file.path=logs/application.log
quarkus.log.file.json=true
quarkus.log.file.json.pretty-print=true  # Pretty JSON format
quarkus.log.file.level=INFO
quarkus.log.console.enable=false
quarkus.log.file.rotation.max-file-size=0
quarkus.log.file.rotation.max-backup-index=0


#JWT

jwt.secret=ThisIsMySecretKey1234
jwt.expiration=3600000

#Profiling
Environment="Development"
#%production.Environment="Production"
#%production.quarkus.http.port=9090
